[package]

name = "sprs"
description = "A sparse matrix library"
version = "0.6.0"
authors = ["Vincent Barrielle <vincent.barrielle@m4x.org>"]

readme = "README.rst"
license = "MIT OR Apache-2.0"
repository = "https://github.com/vbarrielle/sprs"
documentation = "https://vbarrielle.github.io/sprs/doc/sprs/"
keywords = ["sparse", "matrix", "linear", "algebra"]

exclude = [
    "data/*"
]

[dependencies]

num-traits = "0.1.32"
num-complex = "0.1.36"
itertools = "0.6.0"

[dev-dependencies]
tempdir = "0.3.5"


[dependencies.ndarray]
version = "0.10.0"

